In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/unimelb/unimelb_training.csv
/kaggle/input/unimelb/unimelb_example.csv
/kaggle/input/unimelb/unimelb_test.csv


In [2]:
data = pd.read_csv('/kaggle/input/unimelb/unimelb_training.csv')
data.head()

/tmp/ipykernel_20/2348667015.py:1: DtypeWarning: Columns (90,105,119,120,123,124,132,134,135,138,139,147,149,150,153,154,162,164,165,168,169,177,179,183,184,192,194,198,199,207,209,213,214,224,237,239,244) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('/kaggle/input/unimelb/unimelb_training.csv')


Grant.Application.ID  Grant.Status Sponsor.Code Grant.Category.Code  \
0                     1             1          NaN                 NaN   
1                     2             1           2B                 10A   
2                     3             1          29A                 10B   
3                     4             1          40D                 10B   
4                     5             0          59C                 10A   

  Contract.Value.Band...see.note.A Start.date  RFCD.Code.1  RFCD.Percentage.1  \
0                               A     8/11/05     280199.0              100.0   
1                               B    11/11/05     280103.0               30.0   
2                               A    14/11/05     321004.0               60.0   
3                               C    15/11/05     270602.0               50.0   
4                               A    16/11/05     260500.0               34.0   

   RFCD.Code.2  RFCD.Percentage.2  ...  Faculty.No..15  With.PHD.15  \
0          0.0                0.0  ...             NaN          NaN   
1     280106.0               30.0  ...             NaN          NaN   
2     321216.0               40.0  ...             NaN          NaN   
3     320602.0               50.0  ...             NaN          NaN   
4     280000.0               33.0  ...             NaN          NaN   

   No..of.Years.in.Uni.at.Time.of.Grant.15  Number.of.Successful.Grant.15  \
0                                      NaN                            NaN   
1                                      NaN                            NaN   
2                                      NaN                            NaN   
3                                      NaN                            NaN   
4                                      NaN                            NaN   

   Number.of.Unsuccessful.Grant.15  A..15  A.15  B.15  C.15  Unnamed: 251  
0                              NaN    NaN   NaN   NaN   NaN           NaN  
1                              NaN    NaN   NaN   NaN   NaN           NaN  
2                              NaN    NaN   NaN   NaN   NaN           NaN  
3                              NaN    NaN   NaN   NaN   NaN           NaN  
4                              NaN    NaN   NaN   NaN   NaN           NaN  

[5 rows x 252 columns]

In [3]:
len(data.columns)

252

In [4]:
data.columns.tolist()

['Grant.Application.ID',
 'Grant.Status',
 'Sponsor.Code',
 'Grant.Category.Code',
 'Contract.Value.Band...see.note.A',
 'Start.date',
 'RFCD.Code.1',
 'RFCD.Percentage.1',
 'RFCD.Code.2',
 'RFCD.Percentage.2',
 'RFCD.Code.3',
 'RFCD.Percentage.3',
 'RFCD.Code.4',
 'RFCD.Percentage.4',
 'RFCD.Code.5',
 'RFCD.Percentage.5',
 'SEO.Code.1',
 'SEO.Percentage.1',
 'SEO.Code.2',
 'SEO.Percentage.2',
 'SEO.Code.3',
 'SEO.Percentage.3',
 'SEO.Code.4',
 'SEO.Percentage.4',
 'SEO.Code.5',
 'SEO.Percentage.5',
 'Person.ID.1',
 'Role.1',
 'Year.of.Birth.1',
 'Country.of.Birth.1',
 'Home.Language.1',
 'Dept.No..1',
 'Faculty.No..1',
 'With.PHD.1',
 'No..of.Years.in.Uni.at.Time.of.Grant.1',
 'Number.of.Successful.Grant.1',
 'Number.of.Unsuccessful.Grant.1',
 'A..1',
 'A.1',
 'B.1',
 'C.1',
 'Person.ID.2',
 'Role.2',
 'Year.of.Birth.2',
 'Country.of.Birth.2',
 'Home.Language.2',
 'Dept.No..2',
 'Faculty.No..2',
 'With.PHD.2',
 'No..of.Years.in.Uni.at.Time.of.Grant.2',
 'Number.of.Successful.Grant.2',

In [5]:
data.shape

(8708, 252)

In [6]:
data['A.14'].nunique()

0

In [7]:
data.iloc[2,:6]

Grant.Application.ID                       3
Grant.Status                               1
Sponsor.Code                             29A
Grant.Category.Code                      10B
Contract.Value.Band...see.note.A          A 
Start.date                          14/11/05
Name: 2, dtype: object

In [8]:
data['Sponsor.Code'].value_counts()

4D      2006
2B      1741
21A      937
34B      228
24D      171
        ... 
152D       1
171C       1
201A       1
289A       1
329A       1
Name: Sponsor.Code, Length: 297, dtype: int64

In [9]:
data[(np.isnan(data['Person.ID.1'])==False) & (np.isnan(data['Person.ID.3'])==False)][['Person.ID.1','Person.ID.3']]

Person.ID.1  Person.ID.3
2          5967.0      79652.0
6         74292.0      79742.0
14         9067.0      80137.0
29         3067.0      15987.0
32        69262.0     131432.0
...           ...          ...
8672     636677.0     578662.0
8678     907227.0     895287.0
8681      69812.0      66887.0
8682      66637.0      79032.0
8688      72532.0      64867.0

[1128 rows x 2 columns]

In [10]:
data['Person.ID.1'].dtypes

dtype('float64')

In [11]:
data['Person.ID.1'].value_counts()

1797.0      76
67842.0     42
74162.0     38
69812.0     33
85642.0     30
            ..
122022.0     1
360207.0     1
335382.0     1
633697.0     1
53587.0      1
Name: Person.ID.1, Length: 2301, dtype: int64

**Fature Engineering**

In [12]:
data.iloc[2,:].tolist()

[3,
 1,
 '29A',
 '10B',
 'A ',
 '14/11/05',
 321004.0,
 60.0,
 321216.0,
 40.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 730105.0,
 60.0,
 730207.0,
 40.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 5967.0,
 'CHIEF_INVESTIGATOR',
 1955.0,
 'Australia',
 nan,
 2923.0,
 25.0,
 'Yes ',
 '>5 to 10',
 0.0,
 0.0,
 0.0,
 3.0,
 5.0,
 2.0,
 27307.0,
 'CHIEF_INVESTIGATOR',
 1950.0,
 'Australia',
 nan,
 2923.0,
 25.0,
 nan,
 'Less than 0',
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 79652.0,
 'CHIEF_INVESTIGATOR',
 1950.0,
 'Asia Pacific',
 nan,
 2498.0,
 25.0,
 'Yes ',
 'more than 15',
 0.0,
 0.0,
 1.0,
 3.0,
 3.0,
 3.0,
 11667.0,
 'DELEGATED_RESEARCHER',
 1950.0,
 'Australia',
 nan,
 2548.0,
 25.0,
 nan,
 'more than 15',
 0.0,
 0.0,
 6.0,
 14.0,
 12.0,
 2.0,
 nan,
 'EXT_CHIEF_INVESTIGATOR',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'EXT_CHIEF_INVESTIGATOR',
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 'EXT_CHIEF_INVESTIGATOR',
 n

In [13]:
rfcd_pct_cols = ['RFCD.Percentage.1','RFCD.Percentage.2','RFCD.Percentage.3','RFCD.Percentage.4','RFCD.Percentage.5']
rfcd_pct_mean = sum([data[rfcd]*0.01 for rfcd in rfcd_pct_cols])/5.0
rfcd_pct_mean

0       0.2
1       0.2
2       0.2
3       0.2
4       0.2
       ... 
8703    0.2
8704    0.2
8705    NaN
8706    0.2
8707    0.2
Length: 8708, dtype: float64

In [14]:
seo_pct_cols = ['SEO.Percentage.1','SEO.Percentage.2','SEO.Percentage.3','SEO.Percentage.4','SEO.Percentage.5']
seo_pct_mean = sum([data[seo]*0.01 for seo in seo_pct_cols])/5.0
seo_pct_mean

0       0.2
1       0.2
2       0.2
3       0.2
4       0.2
       ... 
8703    0.2
8704    0.2
8705    NaN
8706    0.2
8707    0.2
Length: 8708, dtype: float64

In [15]:
seo_pct_mean[rfcd_pct_mean!=seo_pct_mean] # Hence They are not equal, So can't ignore

23      0.2
25      NaN
26      NaN
50      0.2
57      NaN
       ... 
8655    NaN
8658    0.2
8697    NaN
8702    NaN
8705    NaN
Length: 1080, dtype: float64

In [16]:
year_birth_cols = ['Year.of.Birth.'+str(i) for i in range(1,16)]

max_year_birth = np.nanmax(data[year_birth_cols],axis=1)

max_year_birth

/tmp/ipykernel_20/267228672.py:3: RuntimeWarning: All-NaN axis encountered
  max_year_birth = np.nanmax(data[year_birth_cols],axis=1)


array([1965., 1960., 1955., ..., 1950., 1970., 1960.])

In [17]:
len(max_year_birth)

8708

In [18]:
data['No..of.Years.in.Uni.at.Time.of.Grant.1'].dtypes

dtype('O')

In [19]:
data['No..of.Years.in.Uni.at.Time.of.Grant.1'].value_counts()

>=0 to 5        2830
>5 to 10        1603
Less than 0     1030
>10 to 15        917
more than 15     847
Name: No..of.Years.in.Uni.at.Time.of.Grant.1, dtype: int64

In [20]:
data['No..of.Years.in.Uni.at.Time.of.Grant.3'].value_counts()

>=0 to 5        312
more than 15    198
>5 to 10        171
Less than 0     132
>10 to 15       126
Name: No..of.Years.in.Uni.at.Time.of.Grant.3, dtype: int64

In [21]:
uniyear_cols = ['No..of.Years.in.Uni.at.Time.of.Grant.'+str(i) for i in range(1,16)]
uniyear_cols

['No..of.Years.in.Uni.at.Time.of.Grant.1',
 'No..of.Years.in.Uni.at.Time.of.Grant.2',
 'No..of.Years.in.Uni.at.Time.of.Grant.3',
 'No..of.Years.in.Uni.at.Time.of.Grant.4',
 'No..of.Years.in.Uni.at.Time.of.Grant.5',
 'No..of.Years.in.Uni.at.Time.of.Grant.6',
 'No..of.Years.in.Uni.at.Time.of.Grant.7',
 'No..of.Years.in.Uni.at.Time.of.Grant.8',
 'No..of.Years.in.Uni.at.Time.of.Grant.9',
 'No..of.Years.in.Uni.at.Time.of.Grant.10',
 'No..of.Years.in.Uni.at.Time.of.Grant.11',
 'No..of.Years.in.Uni.at.Time.of.Grant.12',
 'No..of.Years.in.Uni.at.Time.of.Grant.13',
 'No..of.Years.in.Uni.at.Time.of.Grant.14',
 'No..of.Years.in.Uni.at.Time.of.Grant.15']

In [22]:
data[uniyear_cols]

No..of.Years.in.Uni.at.Time.of.Grant.1  \
0                               Less than 0   
1                              more than 15   
2                                  >5 to 10   
3                                  >5 to 10   
4                                  >5 to 10   
...                                     ...   
8703                               >5 to 10   
8704                               >5 to 10   
8705                           more than 15   
8706                              >10 to 15   
8707                              >10 to 15   

     No..of.Years.in.Uni.at.Time.of.Grant.2  \
0                                       NaN   
1                                       NaN   
2                               Less than 0   
3                                  >=0 to 5   
4                                       NaN   
...                                     ...   
8703                                    NaN   
8704                               >=0 to 5   
8705                                    NaN   
8706                                    NaN   
8707                                    NaN   

     No..of.Years.in.Uni.at.Time.of.Grant.3  \
0                                       NaN   
1                                       NaN   
2                              more than 15   
3                                       NaN   
4                                       NaN   
...                                     ...   
8703                                    NaN   
8704                                    NaN   
8705                                    NaN   
8706                                    NaN   
8707                                    NaN   

     No..of.Years.in.Uni.at.Time.of.Grant.4  \
0                                       NaN   
1                                       NaN   
2                              more than 15   
3                                       NaN   
4                                       NaN   
...                                     ...   
8703                                    NaN   
8704                                    NaN   
8705                                    NaN   
8706                                    NaN   
8707                                    NaN   

     No..of.Years.in.Uni.at.Time.of.Grant.5  \
0                                       NaN   
1                                       NaN   
2                                       NaN   
3                                       NaN   
4                                       NaN   
...                                     ...   
8703                                    NaN   
8704                                    NaN   
8705                                    NaN   
8706                                    NaN   
8707                                    NaN   

     No..of.Years.in.Uni.at.Time.of.Grant.6  \
0                                       NaN   
1                                       NaN   
2                                       NaN   
3                                       NaN   
4                                       NaN   
...                                     ...   
8703                                    NaN   
8704                                    NaN   
8705                                    NaN   
8706                                    NaN   
8707                                    NaN   

     No..of.Years.in.Uni.at.Time.of.Grant.7  \
0                                       NaN   
1                                       NaN   
2                                       NaN   
3                                       NaN   
4                                       NaN   
...                                     ...   
8703                                    NaN   
8704                                    NaN   
8705                                    NaN   
8706                                    NaN   
8707                                    NaN   

     No..of.Years.in.Uni.at.Time.of.Grant.8  \
0  

In [23]:
uniyearmap = {'Less than 0':1,'>=0 to 5':2,'>5 to 10':3,'>10 to 15':4,'more than 15':5}
uniyear = data[uniyear_cols].apply(lambda x:x.map(uniyearmap),axis=1)

In [24]:
uniyear

No..of.Years.in.Uni.at.Time.of.Grant.1  \
0                                        1.0   
1                                        5.0   
2                                        3.0   
3                                        3.0   
4                                        3.0   
...                                      ...   
8703                                     3.0   
8704                                     3.0   
8705                                     5.0   
8706                                     4.0   
8707                                     4.0   

      No..of.Years.in.Uni.at.Time.of.Grant.2  \
0                                        NaN   
1                                        NaN   
2                                        1.0   
3                                        2.0   
4                                        NaN   
...                                      ...   
8703                                     NaN   
8704                                     2.0   
8705                                     NaN   
8706                                     NaN   
8707                                     NaN   

      No..of.Years.in.Uni.at.Time.of.Grant.3  \
0                                        NaN   
1                                        NaN   
2                                        5.0   
3                                        NaN   
4                                        NaN   
...                                      ...   
8703                                     NaN   
8704                                     NaN   
8705                                     NaN   
8706                                     NaN   
8707                                     NaN   

      No..of.Years.in.Uni.at.Time.of.Grant.4  \
0                                        NaN   
1                                        NaN   
2                                        5.0   
3                                        NaN   
4                                        NaN   
...                                      ...   
8703                                     NaN   
8704                                     NaN   
8705                                     NaN   
8706                                     NaN   
8707                                     NaN   

      No..of.Years.in.Uni.at.Time.of.Grant.5  \
0                                        NaN   
1                                        NaN   
2                                        NaN   
3                                        NaN   
4                                        NaN   
...                                      ...   
8703                                     NaN   
8704                                     NaN   
8705                                     NaN   
8706                                     NaN   
8707                                     NaN   

      No..of.Years.in.Uni.at.Time.of.Grant.6  \
0                                        NaN   
1                                        NaN   
2                                        NaN   
3                                        NaN   
4                                        NaN   
...                                      ...   
8703                                     NaN   
8704                                     NaN   
8705                                     NaN   
8706                                     NaN   
8707                                     NaN   

      No..of.Years.in.Uni.at.Time.of.Grant.7  \
0                                        NaN   
1                                        NaN   
2                                        NaN   
3                                        NaN   
4                                        NaN   
...                                      ...   
8703                                     NaN   
8704                                     NaN   
8705                                     NaN   
8706                                     NaN   
8707            

In [25]:
uniyear_min = np.nanmin(uniyear,axis=1)
uniyear_min

/tmp/ipykernel_20/2145224201.py:1: RuntimeWarning: All-NaN axis encountered
  uniyear_min = np.nanmin(uniyear,axis=1)


array([1., 5., 1., ..., 5., 4., 4.])

In [26]:
noofsuccess_cols = ['Number.of.Successful.Grant.'+str(i) for i in range(1,16)]
noofsuccess_cols

['Number.of.Successful.Grant.1',
 'Number.of.Successful.Grant.2',
 'Number.of.Successful.Grant.3',
 'Number.of.Successful.Grant.4',
 'Number.of.Successful.Grant.5',
 'Number.of.Successful.Grant.6',
 'Number.of.Successful.Grant.7',
 'Number.of.Successful.Grant.8',
 'Number.of.Successful.Grant.9',
 'Number.of.Successful.Grant.10',
 'Number.of.Successful.Grant.11',
 'Number.of.Successful.Grant.12',
 'Number.of.Successful.Grant.13',
 'Number.of.Successful.Grant.14',
 'Number.of.Successful.Grant.15']

In [27]:
data['Number.of.Successful.Grant.5'].value_counts()

0.0    81
1.0    30
2.0    20
3.0    13
4.0     4
5.0     3
7.0     3
9.0     2
Name: Number.of.Successful.Grant.5, dtype: int64

In [28]:
min_success = np.nanmin(data[noofsuccess_cols],axis=1)
min_success

/tmp/ipykernel_20/3324578939.py:1: RuntimeWarning: All-NaN axis encountered
  min_success = np.nanmin(data[noofsuccess_cols],axis=1)


array([0., 0., 0., ..., 1., 2., 9.])

In [29]:
total_success = np.nansum(data[noofsuccess_cols],axis=1)
total_success

array([0., 0., 0., ..., 1., 2., 9.])

In [30]:
noofunsuccess_cols = ['Number.of.Unsuccessful.Grant.'+str(i) for i in range(1,16)]
noofunsuccess_cols

['Number.of.Unsuccessful.Grant.1',
 'Number.of.Unsuccessful.Grant.2',
 'Number.of.Unsuccessful.Grant.3',
 'Number.of.Unsuccessful.Grant.4',
 'Number.of.Unsuccessful.Grant.5',
 'Number.of.Unsuccessful.Grant.6',
 'Number.of.Unsuccessful.Grant.7',
 'Number.of.Unsuccessful.Grant.8',
 'Number.of.Unsuccessful.Grant.9',
 'Number.of.Unsuccessful.Grant.10',
 'Number.of.Unsuccessful.Grant.11',
 'Number.of.Unsuccessful.Grant.12',
 'Number.of.Unsuccessful.Grant.13',
 'Number.of.Unsuccessful.Grant.14',
 'Number.of.Unsuccessful.Grant.15']

In [31]:
data['Number.of.Unsuccessful.Grant.5'].value_counts()

0.0     69
1.0     28
2.0     25
3.0      9
4.0      6
6.0      5
5.0      3
20.0     2
18.0     2
7.0      1
16.0     1
8.0      1
9.0      1
10.0     1
14.0     1
21.0     1
Name: Number.of.Unsuccessful.Grant.5, dtype: int64

In [32]:
min_unsuccess = np.nanmin(data[noofsuccess_cols],axis=1)
min_unsuccess

/tmp/ipykernel_20/3507670016.py:1: RuntimeWarning: All-NaN axis encountered
  min_unsuccess = np.nanmin(data[noofsuccess_cols],axis=1)


array([0., 0., 0., ..., 1., 2., 9.])

In [33]:
total_unsuccess = np.nansum(data[noofsuccess_cols],axis=1)
len(total_unsuccess)

8708

In [34]:
Astar_cols = ['A..'+str(i) for i in range(1,16)]
Astar_cols

['A..1',
 'A..2',
 'A..3',
 'A..4',
 'A..5',
 'A..6',
 'A..7',
 'A..8',
 'A..9',
 'A..10',
 'A..11',
 'A..12',
 'A..13',
 'A..14',
 'A..15']

In [35]:
data['A..6'].value_counts()

0.0    67
1.0     1
3.0     1
5.0     1
Name: A..6, dtype: int64

In [36]:
total_Astar_papers = np.nansum(data[Astar_cols],axis=1)
total_Astar_papers

array([4., 6., 7., ..., 3., 0., 0.])

In [37]:
A_cols = ['A.'+str(i) for i in range(1,16)]
data['A.2'].value_counts()

0.0     2883
1.0       27
2.0       20
3.0       19
4.0       12
7.0       10
8.0        5
10.0       4
5.0        3
9.0        2
23.0       1
6.0        1
24.0       1
28.0       1
Name: A.2, dtype: int64

In [38]:
total_A = np.nansum(data[A_cols],axis=1)
total_A

array([ 2., 12., 20., ...,  4.,  3., 13.])

In [39]:
B_cols = ['B.'+str(i) for i in range(1,16)]
B_cols

['B.1',
 'B.2',
 'B.3',
 'B.4',
 'B.5',
 'B.6',
 'B.7',
 'B.8',
 'B.9',
 'B.10',
 'B.11',
 'B.12',
 'B.13',
 'B.14',
 'B.15']

In [40]:
total_B = np.nansum(data[B_cols], axis=1)
total_B

array([ 0.,  2., 20., ...,  5.,  7., 12.])

In [41]:
C_cols = ['C.'+str(i) for i in range(1,16)]
total_C = np.nansum(data[C_cols],axis=1)

In [42]:
data['With.PHD.13']

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ... 
8703    NaN
8704    NaN
8705    NaN
8706    NaN
8707    NaN
Name: With.PHD.13, Length: 8708, dtype: object

In [43]:
phd_cols = ['With.PHD.'+str(i) for i in range(1,16)]
has_phd = data[phd_cols].apply(lambda x: 15 - x.isna().sum(), axis=1)
has_phd

0       0
1       1
2       2
3       2
4       1
       ..
8703    1
8704    2
8705    1
8706    1
8707    1
Length: 8708, dtype: int64

In [44]:
data.loc[3,phd_cols]

With.PHD.1     Yes 
With.PHD.2     Yes 
With.PHD.3      NaN
With.PHD.4      NaN
With.PHD.5      NaN
With.PHD.6      NaN
With.PHD.7      NaN
With.PHD.8      NaN
With.PHD.9      NaN
With.PHD.10     NaN
With.PHD.11     NaN
With.PHD.12     NaN
With.PHD.13     NaN
With.PHD.14     NaN
With.PHD.15     NaN
Name: 3, dtype: object

In [45]:
data.iloc[:,:6]

Grant.Application.ID  Grant.Status Sponsor.Code Grant.Category.Code  \
0                        1             1          NaN                 NaN   
1                        2             1           2B                 10A   
2                        3             1          29A                 10B   
3                        4             1          40D                 10B   
4                        5             0          59C                 10A   
...                    ...           ...          ...                 ...   
8703                  8704             1          21A                 50A   
8704                  8705             1          21A                 50A   
8705                  8706             0         137A                 30B   
8706                  8707             1          21A                 50A   
8707                  8708             1          21A                 50A   

     Contract.Value.Band...see.note.A Start.date  
0                                  A     8/11/05  
1                                  B    11/11/05  
2                                  A    14/11/05  
3                                  C    15/11/05  
4                                  A    16/11/05  
...                               ...        ...  
8703                               A    23/12/08  
8704                               A    23/12/08  
8705                              NaN   24/12/08  
8706                               A    24/12/08  
8707                               A    24/12/08  

[8708 rows x 6 columns]

In [46]:
features_df = pd.DataFrame.from_dict(dict({'RFCD_mean':rfcd_pct_mean,'SEO_mean':seo_pct_mean,'max_year_birth':max_year_birth,
                           'uniyear_min':uniyear_min,'min_success':min_success,'total_success':total_success,
                           'min_unsuccess':min_unsuccess,'total_unsuccess':total_unsuccess,'total_Astar_papers':total_Astar_papers,
                           'total_A':total_A,'total_B':total_B,'total_C':total_C,'has_phd':has_phd}))
final_df = pd.concat([data.iloc[:,:6],features_df],axis=1)
final_df.head()

Grant.Application.ID  Grant.Status Sponsor.Code Grant.Category.Code  \
0                     1             1          NaN                 NaN   
1                     2             1           2B                 10A   
2                     3             1          29A                 10B   
3                     4             1          40D                 10B   
4                     5             0          59C                 10A   

  Contract.Value.Band...see.note.A Start.date  RFCD_mean  SEO_mean  \
0                               A     8/11/05        0.2       0.2   
1                               B    11/11/05        0.2       0.2   
2                               A    14/11/05        0.2       0.2   
3                               C    15/11/05        0.2       0.2   
4                               A    16/11/05        0.2       0.2   

   max_year_birth  uniyear_min  min_success  total_success  min_unsuccess  \
0          1965.0          1.0          0.0            0.0            0.0   
1          1960.0          5.0          0.0            0.0            0.0   
2          1955.0          1.0          0.0            0.0            0.0   
3          1975.0          2.0          0.0            0.0            0.0   
4          1965.0          3.0          0.0            0.0            0.0   

   total_unsuccess  total_Astar_papers  total_A  total_B  total_C  has_phd  
0              0.0                 4.0      2.0      0.0      0.0        0  
1              0.0                 6.0     12.0      2.0      2.0        1  
2              0.0                 7.0     20.0     20.0      7.0        2  
3              0.0                 0.0      3.0     13.0      3.0        2  
4              0.0                 3.0      0.0      1.0      0.0        1

In [47]:
final_df.isna().sum()

Grant.Application.ID                   0
Grant.Status                           0
Sponsor.Code                         912
Grant.Category.Code                  912
Contract.Value.Band...see.note.A    3563
Start.date                             0
RFCD_mean                            634
SEO_mean                             664
max_year_birth                       470
uniyear_min                         1056
min_success                          468
total_success                          0
min_unsuccess                        468
total_unsuccess                        0
total_Astar_papers                     0
total_A                                0
total_B                                0
total_C                                0
has_phd                                0
dtype: int64

In [48]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8708 entries, 0 to 8707
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Grant.Application.ID              8708 non-null   int64  
 1   Grant.Status                      8708 non-null   int64  
 2   Sponsor.Code                      7796 non-null   object 
 3   Grant.Category.Code               7796 non-null   object 
 4   Contract.Value.Band...see.note.A  5145 non-null   object 
 5   Start.date                        8708 non-null   object 
 6   RFCD_mean                         8074 non-null   float64
 7   SEO_mean                          8044 non-null   float64
 8   max_year_birth                    8238 non-null   float64
 9   uniyear_min                       7652 non-null   float64
 10  min_success                       8240 non-null   float64
 11  total_success                     8708 non-null   float64
 12  min_un

In [49]:
from datetime import datetime

final_df['Start.date'] = pd.to_datetime(final_df['Start.date'])

In [50]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8708 entries, 0 to 8707
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype         
---  ------                            --------------  -----         
 0   Grant.Application.ID              8708 non-null   int64         
 1   Grant.Status                      8708 non-null   int64         
 2   Sponsor.Code                      7796 non-null   object        
 3   Grant.Category.Code               7796 non-null   object        
 4   Contract.Value.Band...see.note.A  5145 non-null   object        
 5   Start.date                        8708 non-null   datetime64[ns]
 6   RFCD_mean                         8074 non-null   float64       
 7   SEO_mean                          8044 non-null   float64       
 8   max_year_birth                    8238 non-null   float64       
 9   uniyear_min                       7652 non-null   float64       
 10  min_success                       8240 non-null 

In [51]:
final_df['Month'] = final_df['Start.date'].dt.month
final_df.drop('Start.date',axis=1,inplace=True)

In [52]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8708 entries, 0 to 8707
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Grant.Application.ID              8708 non-null   int64  
 1   Grant.Status                      8708 non-null   int64  
 2   Sponsor.Code                      7796 non-null   object 
 3   Grant.Category.Code               7796 non-null   object 
 4   Contract.Value.Band...see.note.A  5145 non-null   object 
 5   RFCD_mean                         8074 non-null   float64
 6   SEO_mean                          8044 non-null   float64
 7   max_year_birth                    8238 non-null   float64
 8   uniyear_min                       7652 non-null   float64
 9   min_success                       8240 non-null   float64
 10  total_success                     8708 non-null   float64
 11  min_unsuccess                     8240 non-null   float64
 12  total_

In [53]:
obj_cols = [col for col in final_df.columns if final_df[col].dtypes=='O']
obj_cols

['Sponsor.Code', 'Grant.Category.Code', 'Contract.Value.Band...see.note.A']

In [54]:
for col in obj_cols:
    final_df[col] = final_df[col].astype('category')
    final_df[col] = final_df[col].cat.codes
final_df.head()

Grant.Application.ID  Grant.Status  Sponsor.Code  Grant.Category.Code  \
0                     1             1            -1                   -1   
1                     2             1           187                    0   
2                     3             1           186                    1   
3                     4             1           236                    1   
4                     5             0           263                    0   

   Contract.Value.Band...see.note.A  RFCD_mean  SEO_mean  max_year_birth  \
0                                 0        0.2       0.2          1965.0   
1                                 1        0.2       0.2          1960.0   
2                                 0        0.2       0.2          1955.0   
3                                 2        0.2       0.2          1975.0   
4                                 0        0.2       0.2          1965.0   

   uniyear_min  min_success  total_success  min_unsuccess  total_unsuccess  \
0          1.0          0.0            0.0            0.0              0.0   
1          5.0          0.0            0.0            0.0              0.0   
2          1.0          0.0            0.0            0.0              0.0   
3          2.0          0.0            0.0            0.0              0.0   
4          3.0          0.0            0.0            0.0              0.0   

   total_Astar_papers  total_A  total_B  total_C  has_phd  Month  
0                 4.0      2.0      0.0      0.0        0      8  
1                 6.0     12.0      2.0      2.0        1     11  
2                 7.0     20.0     20.0      7.0        2     11  
3                 0.0      3.0     13.0      3.0        2     11  
4                 3.0      0.0      1.0      0.0        1     11

In [55]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8708 entries, 0 to 8707
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   Grant.Application.ID              8708 non-null   int64  
 1   Grant.Status                      8708 non-null   int64  
 2   Sponsor.Code                      8708 non-null   int16  
 3   Grant.Category.Code               8708 non-null   int8   
 4   Contract.Value.Band...see.note.A  8708 non-null   int8   
 5   RFCD_mean                         8074 non-null   float64
 6   SEO_mean                          8044 non-null   float64
 7   max_year_birth                    8238 non-null   float64
 8   uniyear_min                       7652 non-null   float64
 9   min_success                       8240 non-null   float64
 10  total_success                     8708 non-null   float64
 11  min_unsuccess                     8240 non-null   float64
 12  total_

In [56]:
final_df.fillna(0,inplace=True)
final_df.isna().sum()

Grant.Application.ID                0
Grant.Status                        0
Sponsor.Code                        0
Grant.Category.Code                 0
Contract.Value.Band...see.note.A    0
RFCD_mean                           0
SEO_mean                            0
max_year_birth                      0
uniyear_min                         0
min_success                         0
total_success                       0
min_unsuccess                       0
total_unsuccess                     0
total_Astar_papers                  0
total_A                             0
total_B                             0
total_C                             0
has_phd                             0
Month                               0
dtype: int64

In [57]:
final_df['Grant.Status'].value_counts()

0    4716
1    3992
Name: Grant.Status, dtype: int64

In [58]:
from sklearn.model_selection import train_test_split

train_X, test_X, train_y, test_y = train_test_split(final_df.drop('Grant.Status',axis=1),final_df['Grant.Status'])

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [59]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

model.fit(train_X,train_y)

RandomForestClassifier()

In [60]:
preds = model.predict(test_X)

In [61]:
from sklearn.metrics import roc_auc_score

roc_auc_score(test_y,preds)

0.8599984161127319